Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false


Style/ClassAndModuleChildren:
  Enabled: false


Style/GuardClause:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false


Lint/MissingSuper:
  Enabled: false
